
# Site settings

url: "http://dansnguyen.github.io" # the base hostname & protocol for your site
# let's you track visitor counts
google_analytics_id: UA-somecode
# point to where this site is hosted on github
github_source_repo: dansnguyen/dansnguyen.github.io

###########################################
# Meta stuff
# this stuff shows up in your site's search results/facebook snippet

title: Dan Nguyen's site
description: "Write an awesome description here of your site. This will also shop up in the search results"
meta_thumbnail_url: http://www.placecage.com/g/500/300
favicon_ico: something.ico



### These things will show up in your footer
twitter_id: dancow
github_id:  dannguyen
tumblr_id: eyeheartnewyork
instagram_id: danwinny
flickr_id: zokuga
youtube_id: dantanguyen
linkedin_id: dan-nguyen/2/570/276

about_url: /about/
contact_url: "/about#contact"
resume_url: http://www.grad.illinois.edu/careerservices/nonacademic/resumes/samples.pdf
email: dun@stanford.edu

#######################################

## You probably don't want to mess with this stuff
markdown: kramdown
baseurl: "" # the subpath of your site, e.g. /blog/
permalink: /posts/:title
sass:
    sass_dir: assets/_sass

