
# Site settings

title: Dan Nguyen's site
email: dun@stanford.edu
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dansnguyen.github.io" # the base hostname & protocol for your site





### other stuff
twitter_username: dancow
github_username:  dannguyen
instagram_username: danwinny
resume_url: http://a.danwin.com
google_analytics_id: UA-somecode

#######################################

# Ignore this stuff
# Build settings
markdown: kramdown
