
# Site settings

title: Dan Nguyen's site
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://dansnguyen.github.io" # the base hostname & protocol for your site

google_analytics_id: UA-somecode
permalink: /posts/:title

sass:
    sass_dir: assets/_sass

### These things will show up in your footer
twitter_id: dancow
github_id:  dannguyen
flickr_id: zokuga
tumblr_id: eyeheartnewyork
instagram_id: danwinny
resume_url: http://a.danwin.com
email: dun@stanford.edu

#######################################

# Ignore this stuff
# Build settings
markdown: kramdown
